default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username : root 
  password :
  host: 127.0.0.1

development:
  <<: *default
  database: smartphone_catalog_dev

test:
  <<: *default
  database: smartphone_catalog_test

production:
  <<: *default
  database: smartphone_catalog_prod