default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: smartphone_catalog_dev

test:
  <<: *default
  database: smartphone_catalog_test
<% if ENV['CI'] %>
  username: root
  password: password
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
<% end %>

production:
  <<: *default
  database: smartphone_catalog_prod