name: CI

env:
  RUBY_VERSION: 2.5.0
  DB_DATABASE: smartphone_catalog_test
  DB_USER: root
  DB_PASSWORD: password
  DB_PORT: 3306
  DB_HOST: 127.0.0.1

on: [push, pull_request]
jobs: 
 rspec-test:
    name: RSpec
    runs-on: ubuntu-20.04
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
        - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          bundler: default
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install dependencies
        run: |
          bundle install
      - name: Create database
        run: |
          sudo apt-get install -y mysql-client libmysqlclient-dev
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot -proot -e "SHOW GRANTS FOR 'root'@'localhost'"
          mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot -proot mysql
          bin/rails db:setup
      - name: Run tests
        env:
          RAILS_ENV: test
          DB_PORT: 3306
        run: rspec spec/*
