name: CI

env:
  RUBY_VERSION: 2.5.0
  DB_DATABASE: smartphone_catalog_test
  DB_USER: root
  DB_PASSWORD: password
  DB_PORT: 33306:3306
  DB_HOST: 127.0.0.1

on: [push, pull_request]
jobs: 
 rspec-test:
    name: RSpec
    runs-on: ubuntu-20.04
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
        - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          bundler: default
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install dependencies
        run: |
          bundle install
      - name: Create database
        run: |
          sudo /etc/init.d/mysql start
          mysql --host ${{ env.DB_HOST }} --port ${{ env.DDB_PORT }} -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
          bin/rails db:setup
      - name: Run tests
        env:
          RAILS_ENV: test
          DB_PORT: 3306
        run: rspec spec/*
