name: CI

env:
  RUBY_VERSION: 2.5.0
  DB_PORT: 3306
  DB_HOST: 127.0.0.1
  MYSQL_USERNAME: root
  MYSQL_PASSWORD: password
  MYSQL_ROOT_PASSWORD: password

on: [push, pull_request]
jobs: 
 rspec-test:
    name: RSpec
    runs-on: ubuntu-20.04
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USERNAME: root
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: smartphone_catalog_test
        ports:
        - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          bundler: default
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install dependencies
        run: |
          bundle install
      - name: Create database
        env:
          DB_PORT: 3306
        run: |
          sudo service mysql start
          bin/rails db:setup
      - name: Run tests
        env:
          RAILS_ENV: test
          DB_PORT: 3306
        run: rspec spec/*
