env:
  RUBY_VERSION: 2.5.0
  DB_PORT: 3306
  DB_HOST: 127.0.0.1

name: Test coverage
on: [push, pull_request]
jobs: 
 rspec-test:
    name: RSpec
    runs-on: ubuntu-20.04
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_PORT: ${{ env.DB_PORT }}
          MYSQL_HOST: ${{ env.DB_HOST }}
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
        - ${{ env.MYSQL_PORT }}
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          bundler: default
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Start mysql
        run: |
          cp config/database.yml.ci config/database.yml
          mysql -h ${{ env.DB_HOST }} --port ${{ env.DB_PORT }} -u root
          sudo /etc/init.d/mysql start
      - name: Install dependencies
        run: |
          bundle install
      - name: Create database
        run: |
          bin/rails db:setup
      - name: Run tests
        env:
          RAILS_ENV: test
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        run: rspec spec/*
